---
- block:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install a few packages that we need for the course
      apt:
        name:
          - virtualbox-{{ virtualbox_version }}
          - vagrant
        state: present

  become: true

- name: Get list of vagrant boxes on machine
  shell: vagrant box list
  register: vagrant_boxes

- name: Output list of vagrant boxes
  debug:
    var: vagrant_boxes

- name: Add vagrant boxes
  shell: vagrant box add {{ item }} --provider virtualbox
  with_items: "{{ vagrant_images }}"
  when: vagrant_boxes.stdout is not search(item)
