---
- name: Get os release name
  command: lsb_release -cs
  register: ubuntu_release

- name: Apt dist upgrade
  apt:
    upgrade: dist
    autoremove: yes

- name: Install official key for virtualbox
  apt_key:
    data: "{{ lookup('file', item) }}"
    state: present
  with_items: 
    - oracle_vbox_2016.asc
    - oracle_vbox.asc

- name: Add repo for virtualbox
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian {{ ubuntu_release.stdout }} contrib"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install a few packages that we need for the course
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox
    - tree

- name: Install vagrant
  apt:
    deb: https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.deb
