---
- block:
    - name: Get os release name
      command: lsb_release -cs
      register: ubuntu_release

    - name: Apt dist upgrade
      apt:
        upgrade: dist
        autoremove: yes

    - name: Install official key for virtualbox
      apt_key:
        data: "{{ lookup('file', item) }}"
        state: present
      with_items: 
        - oracle_vbox_2016.asc
        - oracle_vbox.asc

    - name: Add repo for virtualbox
      apt_repository:
        repo: "deb https://download.virtualbox.org/virtualbox/debian {{ ubuntu_release.stdout }} contrib"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install a few packages that we need for the course
      apt:
        name:
          - virtualbox
          - tree
        state: present

    - name: Install vagrant
      apt:
        name: vagrant
        state: latest
  become: true

- name: Get list of vagrant boxes on machine
  shell: vagrant box list
  register: vagrant_boxes

- name: Output list of vagrant boxes
  debug:
    var: vagrant_boxes

- name: Add vagrant boxes
  shell: vagrant box add {{ item }} --provider virtualbox
  with_items: "{{ vagrant_images }}"
  when: vagrant_boxes.stdout is not search(item)

